name: pk_live

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  http: ^1.2.2
  google_sign_in: ^6.2.1
  permission_handler: ^11.3.1
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.26
  intl: ^0.19.0
  video_player: ^2.8.0
  cached_network_image: ^3.3.1
  agora_rtc_engine: ^6.3.0
  file_picker: ^8.1.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo/app_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "lib/assets/logo/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo/app_logo.png
